Models/AndamentoEntrevista.cs
using System;

namespace ProjetoEstags.Models
{
    public enum AndamentoEntrevista
    {
        Iniciada = 0,
        Agendada = 1,
        Realizada = 2,
        Analise = 3,
        Retorno = 4,
        Concluida = 5
    }
}

Models/Entrevista.cs
using System;

namespace ProjetoEstags.Models
{

    public class Entrevista
    {
        public int Id { get; set; }
        public Entrevistador IdEntrevistador { get; set; }
        public int EntrevistadorId {get; set;}
        public AndamentoEntrevista Andamento { get; set; }
        public Entrevistado IdEntrevistado { get; set; }
        public int EntrevistadoId {get; set;}

        public override string ToString()
        {
            return "IdEntrevistador" + this.IdEntrevistador + " Andamento: " + this.Andamento + " IdEntrevistado: " + IdEntrevistado;
        }

    }

}

Models/Entrevistado.cs
using System;

namespace ProjetoEstags.Models
{
    public class Entrevistado
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public DateTime DataNascimento { get; set; }
        public string Endereco { get; set; }

    }
}

Models/Entrevistador.cs
using System;

namespace ProjetoEstags.Models
{
    public class Entrevistador
    {
        public int Id { get; set; }
        public string NomeEntrevistador { get; set; }
    }
}

Models/ViewModel/CriarEntrevistaViewModel.cs
using System;
using System.Collections.Generic;

namespace ProjetoEstags.Models.ViewModel
{
    public class CriarEntrevistaViewModel
    {
        public ICollection<Entrevistado> Entrevistados { get; set; }
        public ICollection<Entrevistador> Entrevistadores { get; set; }
        public Entrevista Entrevista { get; set; }
        public AndamentoEntrevista AndamentoEntrevista { get; set; }
    }
}

Models/ViewModel/EntrevistaViewModel.cs
using System;
using System.Collections.Generic;

namespace ProjetoEstags.Models.ViewModel
{
    public class EntrevistaViewModel
    {
        public ICollection<Entrevistado> Entrevistados { get; set; }
        public ICollection<Entrevistador> Entrevistadores { get; set; }
        public Entrevista Entrevista { get; set; }
        public AndamentoEntrevista AndamentoEntrevista { get; set; }
    }
}

Controllers/EntrevistaController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ProjetoEstags.Data;
using ProjetoEstags.Models;
using ProjetoEstags.Models.ViewModel;
using ProjetoEstags.Services;

namespace ProjetoEstags.Controllers
{
    public class EntrevistaController : Controller
    {
        private readonly EntrevistadoService _EntrevistadoService;
        private readonly EntrevistadorService _EntrevistadorService;

        private readonly EntrevistaService _EntrevistaService;
        private readonly Context _Context;

        public EntrevistaController(EntrevistadoService entrevistadoService, EntrevistadorService entrevistadorService, Context context, EntrevistaService entrevistaService)
        {
            _EntrevistaService = entrevistaService;
            _EntrevistadoService = entrevistadoService;
            _EntrevistadorService = entrevistadorService;
            _Context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            var entrevistadores = _EntrevistadorService.ListarEntrevistadores();
            var entrevistados = _EntrevistadoService.ListarTodos();
            var viewModel = new CriarEntrevistaViewModel { Entrevistados = entrevistados, Entrevistadores = entrevistadores, AndamentoEntrevista = AndamentoEntrevista.Iniciada };
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Create(Entrevista entrevista)
        {
            _EntrevistaService.AdicionarEntrevista(entrevista);
            return RedirectToAction(nameof(List));
        }

        public IActionResult Search()
        {
            return View();
        }


        public IActionResult List(int? id)
        {

            if (id.HasValue)
            {
                var entrevistas = _EntrevistaService.ListById((int)id);
                return View(entrevistas);
            }
            else
            {
                var entrevistas = _EntrevistaService.ListAll();
                return View(entrevistas);
            }

        }

        public IActionResult ListFinished()
        {
            var entrevistas = _EntrevistaService.ListFinished();
            return View(entrevistas);
        }

        public IActionResult ListPending()
        {
            var entrevistas = _EntrevistaService.ListPending();
            return View(entrevistas);
        }

    }
}

Controllers/EntrevistadoController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjetoEstags.Data;
using ProjetoEstags.Models;
using ProjetoEstags.Services;

namespace ProjetoEstags.Controllers
{
    public class EntrevistadoController : Controller
    {

        private readonly EntrevistadoService _EntrevistadoService;
        private readonly Context _context;

        public EntrevistadoController(Context context, EntrevistadoService service)
        {
            _EntrevistadoService = service;
            _context = context;
        }
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult List()
        {
            var entrevistados = _EntrevistadoService.ListarTodos();
            return View(entrevistados);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(Entrevistado entrevistado)
        {
            _EntrevistadoService.AdicionarEntrevistado(entrevistado);
            return RedirectToAction(nameof(List));
        }
    }
}

Controllers/EntrevistadorController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjetoEstags.Models;
using ProjetoEstags.Services;

namespace ProjetoEstags.Controllers
{
    public class EntrevistadorController : Controller
    {
        private readonly EntrevistadorService _EntrevistadorService;

        public EntrevistadorController(EntrevistadorService service)
        {
            _EntrevistadorService = service;
        }

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> List()
        {
            var entrevistadores = _EntrevistadorService.ListarEntrevistadores();
            return View(entrevistadores);
        }

        [HttpPost]
        public IActionResult CreateAsync(Entrevistador entrevistador)
        {
            _EntrevistadorService.AdicionarEntrevistador(entrevistador);
            return RedirectToAction(nameof(List));
        }
    }
}

Views/Entrevista/Create.cshtml
@model ProjetoEstags.Models.ViewModel.CriarEntrevistaViewModel

<style>
    select,
    button,
    a {
        margin-top: 10px;
        margin-right: 5px;
    }
</style>


<h2 class="h2 text-center" style="color: #FF7200;">Criar uma nova entrevista</h2>
<form asp-action="Create" asp-controller="Entrevista">
    <select asp-for="Entrevista.EntrevistadorId" asp-items="@(new SelectList(Model.Entrevistadores,"Id","NomeEntrevistador"))" class="form-control">
        <option>Escolha o Entrevistador</option>
    </select>
    <select asp-for="Entrevista.Andamento" asp-items="Html.GetEnumSelectList<ProjetoEstags.Models.AndamentoEntrevista>()" class="form-control">
        <option>Status da Entrevista</option>
    </select>
    <select asp-for="Entrevista.EntrevistadoId" asp-items="@(new SelectList(Model.Entrevistados,"Id","Nome"))" class="form-control">
        <option>Escolha o Entrevistado</option>
    </select>
    <a><button class="btn btn-success">Adicionar</button></a>
    <a><button class="btn btn-danger">Cancelar</button></a>
</form>

Views/Entrevista/List.cshtml
@model IEnumerable<Entrevista>

<h2 class="h2 text-center" style="color: #FF7200;">Listagem de todas as Entrevistas</h2>



<table class="table">
  <thead class="thead-primary" style="background-color: #FF7200; color: white;" >
    <tr>
      <th scope="col">#</th>
      <th scope="col">Entrevistado</th>
      <th scope="col">Entrevistador</th>
      <th scope="col">Andamento</th>
    </tr>
  </thead>
  <tbody>
      @foreach (var item in Model)
    {
    <tr>
      <td>@Html.DisplayFor(modelItem => item.Id)</td>
      <td>@Html.DisplayFor(modelItem => item.IdEntrevistado.Nome)</td>
      <td>@Html.DisplayFor(modelItem => item.IdEntrevistador.NomeEntrevistador)</td>
      <td>@Html.DisplayFor(modelItem => item.Andamento)</td>
    </tr>    
    }
</table>

Views/Entrevista/ListFinished.cshtml
@model IEnumerable<Entrevista>

<h2 class="h2 text-center" style="color: #FF7200;">Listagem de todas as Entrevistas</h2>



<table class="table">
  <thead class="thead-primary" style="background-color: #FF7200; color: white;" >
    <tr>
      <th scope="col">#</th>
      <th scope="col">Entrevistado</th>
      <th scope="col">Entrevistador</th>
    </tr>
  </thead>
  <tbody>
      @foreach (var item in Model)
    {
    <tr>
      <td>@Html.DisplayFor(modelItem => item.Id)</td>
      <td>@Html.DisplayFor(modelItem => item.IdEntrevistado.Nome)</td>
      <td>@Html.DisplayFor(modelItem => item.IdEntrevistador.NomeEntrevistador)</td>
    </tr>    
    }
</table>

Views/Entrevista/ListPending.cshtml
@model IEnumerable<Entrevista>

<h2 class="h2 text-center" style="color: #FF7200;">Listagem de todas as Entrevistas</h2>



<table class="table">
  <thead class="thead-primary" style="background-color: #FF7200; color: white;" >
    <tr>
      <th scope="col">#</th>
      <th scope="col">Entrevistado</th>
      <th scope="col">Entrevistador</th>
    </tr>
  </thead>
  <tbody>
      @foreach (var item in Model)
    {
    <tr>
      <td>@Html.DisplayFor(modelItem => item.Id)</td>
      <td>@Html.DisplayFor(modelItem => item.IdEntrevistado.Nome)</td>
      <td>@Html.DisplayFor(modelItem => item.IdEntrevistador.NomeEntrevistador)</td>
    </tr>    
    }
</table>

Views/Entrevista/Search.cshtml
@model Entrevista
<h2 style="color: #FF7200;">Buscar uma entrevista</h2>

<label>Id da entrevista: </label>
<form asp-action="List" asp-controller="Entrevista">
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text">ID</span>
        </div>
        <input asp-for="Id" type="text" class="form-control">
        <input type="submit" class="btn btn-success">
    </div>
</form>

Views/Entrevistado/Create.cshtml
@model ProjetoEstags.Models.Entrevistado

<style>
    input, button
    {
        margin-top: 10px;
        margin-right: 5px;
    }
</style>

<h2 class="h2 text-center" style="color: #FF7200;">Adicionar novo entrevistado</h2>

<form asp-action="Create">
    <input asp-for="Nome" class="form-control" type="text" placeholder="Nome">
    <input asp-for="DataNascimento" class="form-control" type="date" placeholder="Data de Nascimento">
    <input asp-for="Endereco" class="form-control" type="text" placeholder="Endereço">
    <input type="submit" class="btn btn-success" value="Adicionar">
    <button type="submit" class="btn btn-danger">Cancelar</button>
</form>

Views/Entrevistado/List.cshtml
@model IEnumerable<ProjetoEstags.Models.Entrevistado>

<h1 class="h1 text-center" style="color: #FF7200;">Página de listagem dos entrevistados</h1>


<table class="table">
  <thead class="thead-primary" style="background-color: #FF7200; color: white;" >
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Nascimento</th>
      <th scope="col">Endereco</th>
    </tr>
  </thead>
  <tbody>
      @foreach (var item in Model)
    {
    <tr>
      <th scope="row">@Html.DisplayFor(modelItem => item.Id)</th>
      <td>@Html.DisplayFor(modelItem => item.Nome)</td>
      <td>@Html.DisplayFor(modelItem => item.DataNascimento)</td>
      <td>@Html.DisplayFor(modelItem => item.Endereco)</td>
    </tr>    
    }
</table>

Views/Entrevistador/Create.cshtml
@model ProjetoEstags.Models.Entrevistador

<style>
    input,
    button,
    a {
        margin-top: 10px;
        margin-right: 5px;
        
    }
</style>

<form asp-action="Create" asp-controller="Entrevistador">
    <h2 class="h2 text-center" style="color: #FF7200;">Adicionar novo entrevistador</h2>
    <input asp-for="NomeEntrevistador" class="form-control" type="text" placeholder="Nome">
    <input type="submit" class="btn btn-success">
    <a><button class="btn btn-danger">Cancelar</button></a>
</form>

Views/Entrevistador/List.cshtml
@model IEnumerable<ProjetoEstags.Models.Entrevistador>

<h1> Listagem dos Entrevistadores </h1>

<table class="table">
  <thead class="thead-primary" style="background-color: #FF7200; color: white;" >
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
    </tr>
  </thead>
  <tbody>
      @foreach (var item in Model)
    {
    <tr>
      <td>@Html.DisplayFor(modelItem => item.Id)</td>
      <td>@Html.DisplayFor(modelItem => item.NomeEntrevistador)</td>
    </tr>    
    }
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Index.cshtml
<h1>Página de inicio</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoEstags</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg" style="background-color: #FF7200;">
        <h1 style="color: white;"> SGE - Sistema Gerenciador de Entrevistas</h1>
    </nav>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto justify-content-center">
                <li class="nav-item">
                    <a asp-action="Create" asp-controller="Entrevista"><button type="button"
                            class="btn btn-outline-primary">Criar Entrevista</button></a>
                </li>
                <li class="nav-item">
                    <a asp-action="Create" asp-controller="Entrevistado"><button type="button"
                            class="btn btn-outline-primary">Adicionar novo entrevistado</button></a>
                </li>
                <li class="nav-item">
                    <a asp-action="Create" asp-controller="Entrevistador"><button type="button"
                            class="btn btn-outline-primary">Adicionar novo entrevistador</button></a>
                </li>
                <li class="nav-item">
                    <a asp-action="Search" asp-controller="Entrevista"><button type="button"
                            class="btn btn-outline-primary">Buscar uma Entrevista</button></a>
                </li>
                <li class="nav-item">
                    <a asp-action="List" asp-controller="Entrevista"><button type="button"
                            class="btn btn-outline-primary">Listar todas as Entrevistas</button></a>
                </li>
                <li class="nav-item">
                   <a asp-action="ListFinished" asp-controller="Entrevista"><button type="button"
                            class="btn btn-outline-primary">Listar Entrevistas finalizadas</button></a>
                </li>
                <li class="nav-item">
                    <a asp-action="ListPending" asp-controller="Entrevista"><button type="button"
                            class="btn btn-outline-primary">Listar Entrevistas em andamento</button></a>
                </li>
                <li class="nav-item">
                    <a asp-action="List" asp-controller="Entrevistador"><button type="button"
                            class="btn btn-outline-primary">Listar todos os Entrevistadores</button></a>
                </li>
                <li class="nav-item">
                    <a asp-action="List" asp-controller="Entrevistado"><button type="button"
                            class="btn btn-outline-primary">Listar todas os Entrevistados</button></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Projeto dos Estagiários
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>